FROM apache/spark-py

# Set the user to "root"
USER root

# Install any required dependencies
RUN pip install numpy matplotlib pandas

# Set the working directory to /root/project
WORKDIR /root/project

# Copy the real_estate.py file to the container
COPY real_estate.py .

# Switch back to the non-root user provided by the base image
##USER 185

# Specify the command to be executed when the container starts
CMD ["/opt/spark/bin/spark-submit", "real_estate.py"]
